{% set tests_to_skip = "test_http_502" %}
{% set version = "1.6.5" %}

package:
  name: cached_path
  version: {{ version }}

source:
  url: https://github.com/allenai/cached_path/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 93d640232b7168bad7ca9fa2285fe7a631b4f363997ca4942985fb1170786fa3
  patches:
      # upstream expectes the folders /tests & /test_fixtures to be relative
      # to the finished package, even though those folders are not packaged;
      # effectively, the upstream test suite can currently only be run in (their)
      # development mode, so patch it that we can properly test the package here.
    - patches/0001-patch-BaseTestClass-so-that-test-suite-can-be-run-wi.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  # debug this on the feedstock; allennlp stack in conda-forge
  # doesn't support windows yet anyway due to missing pytorch
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - boto3 >=1.0,<2.0
    - filelock >=3.4,<3.14
    - google-cloud-storage >=1.32,<3.0
    - huggingface_hub >=0.8.1,<0.24
    - requests >=2.0,<3.0
    - rich >=12.1,<14
test:
  requires:
    - pytest <8
    - flaky
    - responses
    - pip
  source_files:
    - test_fixtures/
    - tests/
  imports:
    - cached_path
  commands:
    - pip check
    # cannot work here
    {% set tests_to_skip = "test_http_502" %}
    # urrlib3 >=2.0 returns a different error for unreachable urls than cached_path 
    {% set tests_to_skip = tests_to_skip + " or test_http_404 or test_http_500" %}  # [py>39]
    - pytest -v -k "not ({{ tests_to_skip }})"

about:
  home: https://github.com/allenai/cached_path
  license: Apache-2.0
  license_file: LICENSE
  summary: A file utility for accessing both local and remote files through a unified interface.
  dev_url: https://github.com/allenai/cached_path
  doc_url: https://cached-path.readthedocs.io/

extra:
  recipe-maintainers:
    - h-vetinari
    - xhochy
