# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.8.0"
  tests_to_skip: not test_http_502
  python_check_max: "3.14"

package:
  name: cached_path
  version: ${{ version }}

source:
  url: https://github.com/allenai/cached_path/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 340d0a2a87b82450c810d62f3d293f263c8c555c0b6bfc2cec36d1e176730dc5
  patches:
    # upstream expectes the folders /tests & /test_fixtures to be relative
    # to the finished package, even though those folders are not packaged;
    # effectively, the upstream test suite can currently only be run in (their)
    # development mode, so patch it that we can properly test the package here.
    - patches/0001-patch-BaseTestClass-so-that-test-suite-can-be-run-wi.patch

build:
  number: 1
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - boto3 >=1.0,<2.0
    - filelock >=3.4,<4.0
    - google-cloud-storage >=1.32,<3.0
    - huggingface_hub >=0.8.1,<1.0
    - python >=${{ python_min }}
    - requests >=2.0,<3.0
    - rich >=12.1,<14

tests:
  - python:
      imports: cached_path
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      source:
        - test_fixtures/
        - tests/
    requirements:
      run:
        - flaky
        - pytest
        - python ${{ python_min }}.*
        - responses
    script:
      - pytest -vv --tb=long --color=yes -k "${{ tests_to_skip }}"

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: A file utility for accessing both local and remote files through a unified interface.
  homepage: https://github.com/allenai/cached_path
  repository: https://github.com/allenai/cached_path
  documentation: https://cached-path.readthedocs.io/

extra:
  recipe-maintainers:
    - h-vetinari
    - xhochy
