# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.8.1"
  # urrlib3 >=2.0 returns a different error for unreachable urls than cached_path 
  tests_to_skip: not (test_http_404 or test_http_500 or test_http_502)
  python_check_max: "3.13"
  #   File "$SRC_DIR_env/lib/python3.14/site-packages/google/cloud/storage/blob.py", line 21, in <module>
  #       import cgi
  #   ModuleNotFoundError: No module named 'cgi'
  # python_check_max: "3.14"

package:
  name: cached_path
  version: ${{ version }}

source:
  url: https://github.com/allenai/cached_path/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 3afbcf5316e7a3a0cf94d881ae108eca3f09c792d282184c85ba92ddde07d117

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - boto3 >=1.0,<2.0
    - filelock >=3.4,<4.0
    - google-cloud-storage >=1.32,<3.0
    - huggingface_hub >=0.8.1,<1.0
    - packaging
    - python >=${{ python_min }}
    - requests
    - rich >=12.1,<14.0

tests:
  - python:
      imports: cached_path
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - files:
      source:
        - test_fixtures/
        - tests/
    requirements:
      run:
        - flaky
        - pytest
        - python ${{ python_min }}.*
        - responses
    script:
      # upstream expects the folders /tests & /test_fixtures to be relative
      # to the finished package, so copy them into the test `site-packages`.
      - python -c "import shutil, site; sp = site.getsitepackages()[0]; [shutil.copytree(p, f'{sp}/{p}') for p in ['tests', 'test_fixtures']]"
      - pytest -vv --tb=long --color=yes -k "${{ tests_to_skip }}"

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: A file utility for accessing both local and remote files through a unified interface.
  homepage: https://github.com/allenai/cached_path
  repository: https://github.com/allenai/cached_path
  documentation: https://cached-path.readthedocs.io/

extra:
  recipe-maintainers:
    - h-vetinari
    - xhochy
